<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_alat</name>
   <tag></tag>
   <elementGuidId>a5d6520f-7119-4c6f-8552-eb9d3e0a7fad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div/div[2]/div/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#list-item-765-2 > div.v-list-item__content</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;list-item-765-2&quot;)/div[@class=&quot;v-list-item__content&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>51318ef9-fbe1-4b9e-af78-44db66cace05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-list-item__content</value>
      <webElementGuid>d6461675-8f66-4ecd-b501-6183e6e858d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>kesehatan</value>
      <webElementGuid>89f24934-2825-4bbb-845e-b935b43af821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list-item-765-2&quot;)/div[@class=&quot;v-list-item__content&quot;]</value>
      <webElementGuid>0cff11eb-f375-4a42-aaea-4226cc442d25</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-item-765-2']/div</value>
      <webElementGuid>84ca0878-3fbb-4fc6-9899-d3d1138d7e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kesehatan'])[2]/following::div[2]</value>
      <webElementGuid>367d627c-6a84-4a73-8985-6def285527a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kesehatan'])[1]/following::div[5]</value>
      <webElementGuid>50678d2e-29d3-411a-a8e9-15734c858a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='alat'])[2]/preceding::div[2]</value>
      <webElementGuid>572e041d-aee8-472d-8ff5-77bae75dc71c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/div</value>
      <webElementGuid>ca55a0af-3991-413e-b59b-d6a578a6375b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'alat' or . = 'alat')]</value>
      <webElementGuid>fc16a85c-a060-4562-b5e3-0964a4416a6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
